# Generated by Django 3.2.5 on 2021-07-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_rescata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
