# Generated by Django 3.2.5 on 2021-07-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_rescata', '0002_alter_tipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
